function [i1, i2, i3, i4] = i1234(Zout, DT)

arg = sqrt(2/pi/DT)*Zout;

i1 = ((-1 + 1i)*sqrt(pi/2.)*(-1 + (1 + 1i)*fresnelc(arg) ...
    + (1 - 1i)*fresnels(arg)))/Zout;

i2 = (2*sqrt(DT))/exp((1i*Zout^2)/DT) + ...
    (1 + 1i)*sqrt(2*pi)*Zout*(-1 + (1 + 1i)*fresnelc(arg) ...
    + (1 - 1i)*fresnels(arg));

i3 = ((1 - 1i)*sqrt(DT)*sqrt(pi/2.))/(exp((1i*Zout^2)/DT)*Zout) ...
    + pi*(-1 + (1 + 1i)*fresnelc(arg) ...
    +(1 - 1i)*fresnels(arg));

i4 = (((-1 - 1i)*sqrt(DT)*sqrt(2*pi)*Zout)/exp((1i*Zout^2)/DT) ...
    - pi*(DT + 2*1i*Zout^2)*(-1 + (1 + 1i)*fresnelc(arg) ...
    + (1 - 1i)*fresnels(arg)))/2.;

end

